# -*- coding: utf-8 -*-
"""Generates `lib/app_info.dart`.

The app needs three facts about itself that only the build knows: its own
version, the catalog version compiled into it, and the schema that catalog
speaks. Reading them back out of the asset at start-up would mean unpacking a
multi-megabyte file on every launch just to compare two strings, so the build
writes them down instead.
"""
from __future__ import annotations

import pathlib
import re

from .model import CATALOG_SCHEMA_VERSION, Catalog

HEADER = '// GENERATED by tool/build_catalog.py — do not edit by hand.'


def read_app_version(root: pathlib.Path) -> str:
    """The `version:` line of pubspec.yaml without its build number."""
    text = (root / 'pubspec.yaml').read_text(encoding='utf-8')
    match = re.search(r'^version:\s*([0-9]+\.[0-9]+\.[0-9]+)', text, re.M)
    if not match:
        raise SystemExit('pubspec.yaml has no parseable version')
    return match.group(1)


def read_release_key(root: pathlib.Path) -> str:
    """The public key releases are signed with, or an empty string.

    Empty means signing is not switched on for this project yet: the client
    then verifies SHA-256 and trusts HTTPS to the forge, which is what it did
    before signing existed. A non-empty key is a promise — an app carrying one
    refuses a catalog that is not signed by it.
    """
    path = root / 'data' / 'release-key.pub'
    return path.read_text(encoding='utf-8').strip() if path.exists() else ''


def write_app_info(catalog: Catalog, root: pathlib.Path) -> pathlib.Path:
    path = root / 'lib' / 'app_info.dart'
    body = f"""{HEADER}

/// Version of this build, taken from pubspec.yaml.
const appVersion = '{read_app_version(root)}';

/// Catalog compiled into `assets/catalog.db`.
///
/// Compared against the installed database on start-up: a fresh app build
/// carrying a newer catalog replaces the file an older install left behind,
/// without waiting for a download.
const bundledCatalogVersion = '{catalog.version}';

/// Layout of the database this build knows how to read.
const bundledCatalogSchema = {CATALOG_SCHEMA_VERSION};

/// Entries in the bundled catalog, for the empty and error states.
const bundledCatalogItemCount = {len(catalog.items)};

/// Ed25519 public key that catalog releases are signed with, base64, or empty.
///
/// Empty disables signature checking: downloads are still verified against the
/// SHA-256 in the manifest, which is itself fetched over HTTPS. Non-empty makes
/// a signature mandatory — an unsigned or wrongly signed catalog is refused
/// rather than installed. Set from data/release-key.pub; see SECURITY.md.
const releasePublicKey = '{read_release_key(root)}';
"""
    path.write_text(body, encoding='utf-8')
    return path
